### ISSUE TITLE
"scan" is not exported by "node_modules/react-scan/dist/rsc-shim.mjs"

### ISSUE THREAD

**Issue by mrlubos** [aidenybai/react-scan#125] opened 2024-12-16 19:34 UTC
Hey! Giving this a try and everything works locally, nice! However, when I try to create a production build of my Vite application, I see the following error.

```sh
src/index.tsx (7:9): "scan" is not exported by "node_modules/react-scan/dist/rsc-shim.mjs", imported by "src/index.tsx".
```

Let me know what else you need to be able to debug!

**Comment by aidenybai** [comment] 2024-12-22 02:42
hi @mrlubos, this will be fixed on the latest version. it looks like this is being used in a react server / remix? context, what is your current project setup?

**Comment by mrlubos** [comment] 2024-12-22 04:51
Thanks! I'll give it a try.

Nope, a relatively basic Vite SPA setup with TypeScript! I'm not sure what you're looking for, I could try to reproduce if the problem persists and you've got a starter template

**Comment by pivanov** [comment] 2024-12-25 18:48
Hey @darklight9811 
Can you check this example [vite-react-scan](https://github.com/pivanov/vite-react-scan)?
It's simple `npm create vite@latest` app.

Is this helps? If not please provide a simple repo where we can reproduce the issue.

**Comment by darklight9811** [comment] 2024-12-26 07:27
@pivanov got fixed in `0.0.54` or `0.0.53` (didnt test this version), but was broken on `0.0.52`. The issue is solved.

BTW, would be really helpful if you had releases with changelog here in github

**Comment by pivanov** [comment] 2024-12-26 07:42
Yep we are working on this ... hope we will have them soon.
I will close this one for now :) Thanks again!

**Closed by pivanov** 2024-12-26 07:42 UTC

**Comment by pivanov** [comment] 2025-01-16 21:34
@mrlubos 
For Vite you can check this one [@pivanov/vite-plugin-react-scan](https://www.npmjs.com/package/@pivanov/vite-plugin-react-scan) :)

please let me know how it's work.
